if: branch = master

sudo: required

language: python

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

install:
  - pip install htmldiffer

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ asciidoctor/docker-asciidoctor asciidoctor -a data-uri sslgoals.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf -a scripts=cjk -a pdf-theme=default-with-fallback-font sslgoals.adoc

after_error:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_script:
  - git clone https://${GH_REF} --single-branch --branch gh-pages $TRAVIS_BUILD_DIR/gh-pages
  - cd $TRAVIS_BUILD_DIR/gh-pages
  - cp ../*.html ../*.pdf .
  # - python ../diffHtml.py ./2020/sslgoals.html ./sslgoals.html > sslgoals-diff.html
  - git config user.name "TravisCI"
  - git config user.email "build-pipeline@travis-ci.org"
  - git add *.html *.pdf
  - git commit -m "Update GitHub Pages"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages
